services:
  - type: web
    name: grayknight-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: grayknight-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

databases:
  - name: grayknight-db
    region: singapore
    plan: free
    ipAllowList: []
